### ISSUE TITLE
Prepare bills and summaries as datasets

### ISSUE THREAD

**Issue by aih** [dreamproit/BillML#1]
This repository is to download bill and summaries from GovInfo or the Congress.gov API and prepare them for datasets to upload to Huggingface.

The bills and summaries are available as bulk data from:
https://www.govinfo.gov/bulkdata

In particular, uslm xml is here:
https://www.govinfo.gov/bulkdata/BILLS/uslm

Bill summaries are here:
https://www.govinfo.gov/bulkdata/BILLSUM

A guideline to bill summaries is here:
https://www.govinfo.gov/bulkdata/BILLSUM/resources

In order to improve quality of ML results, the first goal is to collect into a data set, bill text and bill summary from bills that have fewer than 10 sections. (The length of sections can be parsed with lxml.  See comment below).

**Comment by aih** [comment]
This is a sample function, using lxml and namespaces, to parse sections. This is used with the US Code, but the same function should work with bills.

https://github.com/aih/SearchUSCode/blob/main/scripts/elastic_load.py#L48
```python
def getSections(doc_path: str=PATH_USC_TITLE_16, ns=NS_USLM):
    try:
      docTree = etree.parse(doc_path)
    except Exception as e:
      import sys
      raise type(e)(str(e) +
                      '; Could not parse document').with_traceback(sys.exc_info()[2])

    logging.info('Getting sections for: ' + doc_path)
    return docTree.xpath('//uslm:section[not(ancestor::uslm:section)]', namespaces=ns)
```

**Comment by aih** [comment]
@davanstrien may provide recommendations for how to structure the data into datasets. Perhaps a few variations-- 
`{billxml: [bill in xml]
   summary: [summary in xml]
}`
`{billtext: [serialized text of bill],
    summarytext: [ serialized text of summary]
}
`
And possibly other variations with sections separated into their own object/field?

**Comment by davanstrien** [comment]
Here are some quick thoughts on this. Apologies if I say stuff people are already familiar with. 

## Summarization models 
> Summarization is the task of producing a shorter version of a document while preserving its important information. Some models can extract text from the original input, while other models can generate entirely new text.
source: [https://huggingface.co/tasks/summarization]()

I'm unsure with the bill summaries if they tend to extract text from the original bill or reformulate the bill's intention using new language. 

Most of these models (at least those I am aware of) don't consider markup associated with the document. i.e. they take in plain text and spit out plain text.  

Some new language models aim to incorporate markup information, for example, https://huggingface.co/docs/transformers/main/en/model_doc/markuplm#markuplm. 

In the case of these bills, it would seem that the XML markup will contain useful information for the model. One approach would be to manually write some rules to parse the XML into a subset that would you think would be most useful for summarization. The other approach would be to try and let the model work this out.

## Dataset structure 

> @davanstrien may provide recommendations for how to structure the data into datasets. Perhaps a few variations-- `{billxml: [bill in xml] summary: [summary in xml] }` `{billtext: [serialized text of bill], summarytext: [ serialized text of summary] } ` And possibly other variations with sections separated into their own object/field?

This sounds sensible, basically; since there is an open research question about how to best tackle this problem, it would be useful to offer different 'inputs' and 'target' columns that can be used to help assess what approach is most useful. 

Another challenge of this data might be the length of the text. Many models expect a max sequence length to be relatively short see https://huggingface.co/docs/transformers/main/en/model_doc/markuplm#transformers.MarkupLMConfig.max_position_embeddings. There are different ways of tackling this:
- use a different model like BigBird https://huggingface.co/docs/transformers/main/en/model_doc/big_bird
- various sliding window approaches etc. 

I mention this because you may want to think about whether it makes sense to already split the text into shorter parts. From my brief discussion with @aih, I get the impression that the bills aren't summarized in parts, i.e. a summary for each page of the bill but instead, the summary is done for the entire bill. If this is the case, it's probably better to leave decisions about splitting longer texts to the people using the dataset. 

Here are some other datasets for this task that could be useful https://huggingface.co/datasets?task_categories=task_categories:summarization&sort=downloads

**Comment by aih** [comment]
These are all valuable suggestions.

> whether it makes sense to already split the text into shorter parts

This is natural and easy to do at the section level. If we start by limiting the dataset to bills with 10 sections or fewer, we can have the sections listed within the dataset. From the dataset examples @davanstrien links to above, I see this approach to sections (for PubMed articles). One thing I wonder about with this is that section titles and section text are separated into separate lists. I would prefer to link them (e.g. as a list of objects with `title` and `text` keys), if that is a feasible input to a model.

https://huggingface.co/datasets/ccdv/pubmed-summarization/blob/main/pubmed-summarization.py

```python


def _generate_examples(self, filepath):
--
  | """Generate PubMedSummarization examples."""
  | with open(filepath, encoding="utf-8") as f:
  | for id_, row in enumerate(f):
  | data = json.loads(row)
  |  
  | """
  | 'article_id': str,
  | 'abstract_text': List[str],
  | 'article_text': List[str],
  | 'section_names': List[str],
  | 'sections': List[List[str]]
  | """
  | if self.config.name == "document":
  | article = [d.strip() for d in data["article_text"]]
  | article = " ".join(article)
  | else:
  | article = [item.strip() for sublist in data["sections"] for item in sublist]
  | article = " \n ".join(article)
  |  
  | abstract = [ab.replace("<S>", "").replace("</S>", "").strip() for ab in data["abstract_text"]]
  | abstract = " \n ".join(abstract)
  | yield id_, {"article": article, "abstract": abstract}
```

**Comment by aih** [comment]
The base dataset is done and stored in this repo's wiki.
